spring:
  application:
    name: Mail Service
  mail:
    host: smtp.gmail.com
    port: 465
    username: <EMAIL>
    password: <PASSWORD>
    ssl:
      enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


server:
  port: 8082

custom:
  datasource:
      baseUrl: http://localhost:8432/api/
  queue:
    verification: verificationQueue
    notification: notificationQueue